@startuml

!include <C4/C4_Container>

Person(User, "Пользователь")
Person(EmployeeBack, "Сотрудник бэк-офиса")
Person(EmployeeFront, "Сотрудник фронт-офиса")

System_Boundary(ABC_Boundary, "АБС - Банковская система") {
    Container(ABC, "АБС", "Delphi")
    Container(API_ABC, "АПИ АБС", "Java") #green
    ContainerDb(ABC_Db, "АБС база данных", "Oracle")
    
    Rel(ABC, API_ABC, "Вызов процедур", "HTTP/JSON")
    Rel(API_ABC, ABC_Db, "Вызов процедур", "PL-SQL")
}

System_Boundary(InternetBankSystem, "Интернет-банк") {
    Container(InternetBank_Monolith, "Сервис интернет-банк", "ASP.NET MVC 4.5", "Монолит")
    ContainerDb(InternetBankDb, "База данных\n интернет-банка", "MSSQL")
    
    
    Rel(InternetBank_Monolith, InternetBankDb, "")
    
}


System_Boundary(DepositSrvice, "Сервис депозитов") {
    
    Container(InternetBank_Deposit, "Микросервис депозитов", "Java") #green
    ContainerDb(InternetBank_DepositDb, "База данных депозитов", "Oracle") #green
    
    Rel(InternetBank_Deposit, InternetBank_DepositDb, "")
    
    Rel(InternetBank_Monolith, InternetBank_Deposit, "Делает запросы", "HTTP/JSON")
}

System_Ext(SMS, "СМС-Шлюз")

Rel(User, InternetBank_Monolith, "Использует")
Rel(EmployeeBack, ABC, "Использует")
Rel(EmployeeFront, ABC, "Использует")

Rel(ABC, SMS, "Отправка СМС")
Rel(InternetBank_Deposit, API_ABC, "Отправка заявок")

@enduml